title: Ryan's Wild Ride
description: Come Follow Along as I Travel Around South America
show_downloads: false

baseurl: "/travel-blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://ry-werth.github.io" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: jekyll-theme-cayman

#  admins:
